1. Write a Python program using list comprehension to filter out numbers divisible by both 5 and 7
from the list [12, 24, 35, 70, 88, 120, 155] and then sort the remaining numbers in descending order.

In [14]:
numbers = [12, 24, 35, 70, 88, 120, 155]

print("The numbers that are divisible by 5 and 7 are : ")

for i in numbers:
    if (i%5==0) and (i%7==0):
        print(i)

filtered_numbers = [num for num in numbers if not (num % 5 == 0 and num % 7 == 0)]

# Sorting the remaining numbers in descending order
sorted_numbers = sorted(filtered_numbers, reverse=True)

print("\nThe filtered and sorted list is:", sorted_numbers)

The numbers that are divisible by 5 and 7 are : 
35
70

The filtered and sorted list is: [155, 120, 88, 24, 12]


--------------------------------------------------------------------------------------------------------------------------------------
2. Create a Python program using list comprehension to remove elements at prime indices from the
list [12, 24, 35, 70, 88, 120, 155, 200, 301, 405].

In [16]:
# Function to check if a number is prime
def is_prime(n):
    if n <= 1:
        return False
    if n == 2:
        return True
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            return False
    return True

# Original list
numbers = [12, 24, 35, 70, 88, 120, 155, 200, 301, 405]

# List comprehension to remove elements at prime indices
filtered_numbers = [num for i, num in enumerate(numbers) if not is_prime(i)]

print("The list after removing elements at prime indices is:", filtered_numbers)

The list after removing elements at prime indices is: [12, 24, 88, 155, 301, 405]


---------------------------------------------------------------------------------------------------------------------------------
3. Generate a 3x5x8 3D array filled with random integers between 1 and 100 using list
comprehension.

In [18]:
import random

# Generate a 3x5x8 3D array with random integers between 1 and 100
array_3d = [[[random.randint(1, 100) for num in range(8)] for num in range(5)] for num in range(3)]

# Print the 3D array
for layer in array_3d:
    for row in layer:
        print(row)
    print()  # Adding a blank line between layers 

[97, 18, 47, 88, 29, 35, 67, 50]
[95, 91, 3, 55, 7, 27, 3, 21]
[84, 9, 73, 80, 13, 79, 37, 50]
[13, 12, 22, 35, 89, 76, 23, 50]
[97, 63, 52, 94, 10, 80, 71, 67]

[76, 58, 84, 86, 59, 28, 58, 36]
[95, 63, 96, 61, 87, 44, 98, 90]
[96, 88, 32, 19, 86, 42, 53, 89]
[66, 62, 96, 75, 94, 88, 54, 30]
[17, 19, 26, 37, 35, 36, 1, 76]

[92, 74, 78, 89, 47, 39, 57, 82]
[60, 29, 65, 12, 31, 23, 74, 24]
[13, 4, 40, 64, 57, 59, 64, 74]
[85, 1, 46, 13, 9, 45, 60, 6]
[50, 53, 51, 89, 21, 66, 77, 7]



---------------------------------------------------------------------------------------------------------------------------
4. Write a Python program to remove elements at the 0th, 4th, and 5th positions from the list [12, 24,
35, 70, 88, 120, 155] using a loop and list comprehension.

In [19]:
numbers = [12, 24, 35, 70, 88, 120, 155]

# Positions to remove
positions_to_remove = [0, 4, 5]

# List comprehension to remove elements at specified positions
filtered_numbers = [num for i, num in enumerate(numbers) if i not in positions_to_remove]

print("The list after removing elements at 0th, 4th, and 5th positions is:", filtered_numbers)

The list after removing elements at 0th, 4th, and 5th positions is: [24, 35, 70, 155]


---------------------------------------------------------------------------------------------------------------------------------
5. Create a Python program to remove all instances of the number 24 from the list [12, 24, 35, 24,
88, 120, 155] and then double the remaining elements using list comprehension.

In [21]:
numbers = [12, 24, 35, 24, 88, 120, 155]

# List comprehension to remove all instances of 24 and double the remaining elements
processed_numbers = [num * 2 for num in numbers if num != 24]

print("The list after removing 24 and doubling the remaining elements is:", processed_numbers)


The list after removing 24 and doubling the remaining elements is: [24, 70, 176, 240, 310]


------------------------------------------------------------------------------------------------------------------------------------
6. Given two lists [1, 3, 6, 78, 35, 55] and [12, 24, 35, 24, 88, 120, 155], write a program to find their
intersection, sort it in ascending order, and remove any duplicates.

In [22]:
list1 = [1, 3, 6, 78, 35, 55]
list2 = [12, 24, 35, 24, 88, 120, 155]

# Find intersection and remove duplicates using set
intersection = set(list1) & set(list2)

# Convert to a sorted list
sorted_intersection = sorted(intersection)

print("The sorted intersection of the two lists without duplicates is:", sorted_intersection)

The sorted intersection of the two lists without duplicates is: [35]


-------------------------------------------------------------------------------------------------------------------------------------
7. Write a Python program to remove duplicate values from the list [12, 24, 35, 24, 88, 120, 155, 88,
120, 155] while preserving the original order, and then reverse the list.

In [23]:
numbers = [12, 24, 35, 24, 88, 120, 155, 88, 120, 155]

# Function to remove duplicates.
def remove_duplicates_preserve_order(lst):
    seen = set()
    result = []
    for item in lst:
        if item not in seen:
            seen.add(item)
            result.append(item)
    return result

# Remove duplicates while preserving order
unique_numbers = remove_duplicates_preserve_order(numbers)

# Reverse the list
reversed_unique_numbers = unique_numbers[::-1]

print("The list after removing duplicates, preserving order, and reversing is:", reversed_unique_numbers)


The list after removing duplicates, preserving order, and reversing is: [155, 120, 88, 35, 24, 12]


---------------------------------------------------------------------------------------------------------------------------------------
8. Define a class `Person` and two subclasses `Male` and `Female`. Each subclass should have a
method `getGender` that prints 'Male' for the `Male` class and 'Female' for the `Female` class.
Create a list of `Person` objects and filter out only the males using list comprehension.

In [24]:
# Person class
class Person:
    def getGender(self):
        pass

# Male subclass
class Male(Person):
    def getGender(self):
        return "Male"

# Female subclass
class Female(Person):
    def getGender(self):
        return "Female"

# list of Person objects
people = [Male(), Female(), Male(), Female(), Male()]

# Filter out only the males using list comprehension
males = [person for person in people if person.getGender() == "Male"]

print("Filtered list of males:")
for male in males:
    print(male.getGender())


Filtered list of males:
Male
Male
Male


-----------------------------------------------------------------------------------------------------------------------------------
9. Create a Python program that counts and prints the frequency of each character in a given string
input from the console, ignoring spaces and punctuation.

In [26]:
import string

# Function to count character frequencies
def count_character_frequencies(input_string):
    # A dictionary to store character frequencies
    frequencies = {}
    
    # Iterate through each character in the string
    for char in input_string:
        # Ignore spaces and punctuation
        if char not in string.whitespace and char not in string.punctuation:
            # Convert character to lowercase to count case-insensitively
            char = char.lower()
            # Update the frequency count
            if char in frequencies:
                frequencies[char] += 1
            else:
                frequencies[char] = 1
    
    return frequencies

# Get input from the console
input_string = input("Enter a string: ")

# Get the character frequencies
frequencies = count_character_frequencies(input_string)

# Print the character frequencies
print("Character frequencies (ignoring spaces and punctuation):")
for char, count in frequencies.items():
    print(f"{char}: {count}")


Enter a string:  My name is shahid ullah.


Character frequencies (ignoring spaces and punctuation):
m: 2
y: 1
n: 1
a: 3
e: 1
i: 2
s: 2
h: 3
d: 1
u: 1
l: 2


----------------------------------------------------------------------------------------------------------------------------------
10. Write a Python program that accepts a string from the console, reverses the string, and checks if
the reversed string is a palindrome.

In [30]:
# Function to check if a string is a palindrome
def is_palindrome(s):
    # Remove spaces and convert to lowercase for case-insensitive comparison
    cleaned_string = ''.join(c.lower() for c in s if c.isalnum())
    
    # Reverse the cleaned string
    reversed_string = cleaned_string[::-1]
    
    # Check if the cleaned string is equal to the reversed string
    return cleaned_string == reversed_string

# Get input from the console
input_string = input("Enter a string: ")

# Check if the input string is a palindrome
if is_palindrome(input_string):
    print("The string is a palindrome.")
else:
    print("The string is not a palindrome.")


Enter a string:  is si


The string is a palindrome.


----------------------------------------------------------------------------------------------------------------------------------
11. Write a Python program to generate a 2D array of size 5x5 with random values between 1 and
50 and then replace all even numbers with -1.

In [31]:
import random

# Generate a 2D array of size 5x5 with random values between 1 and 50
array_2d = [[random.randint(1, 50) for num in range(5)] for num in range(5)]

# Print the original 2D array
print("2D array:")
for row in array_2d:
    print(row)

# Replace all even numbers with -1 using list comprehension
modified_array_2d = [[-1 if num % 2 == 0 else num for num in row] for row in array_2d]

# Print the modified 2D array
print("\nModified 2D array (even numbers replaced with -1):")
for row in modified_array_2d:
    print(row)


2D array:
[10, 5, 14, 6, 36]
[42, 42, 20, 19, 28]
[40, 39, 29, 17, 20]
[46, 38, 22, 1, 12]
[32, 24, 46, 10, 14]

Modified 2D array (even numbers replaced with -1):
[-1, 5, -1, -1, -1]
[-1, -1, -1, 19, -1]
[-1, 39, 29, 17, -1]
[-1, -1, -1, 1, -1]
[-1, -1, -1, -1, -1]


-----------------------------------------------------------------------------------------------------------------------------------
12. Create a Python function that takes a string and returns a dictionary where the keys are
characters and the values are the count of their occurrences, excluding spaces and
case-insensitively.

In [32]:
def count_character_occurrences(s):
    # A dictionary to store character counts
    char_count = {}
    
    # Iterate over each character in the string
    for char in s:
        # Ignore spaces
        if char != ' ':
            # Convert character to lowercase.
            char = char.lower()
            
            # Update the count in the dictionary
            if char in char_count:
                char_count[char] += 1
            else:
                char_count[char] = 1
    
    return char_count

input_string = "Hello World"
result = count_character_occurrences(input_string)
print(result)

{'h': 1, 'e': 1, 'l': 3, 'o': 2, 'w': 1, 'r': 1, 'd': 1}


----------------------------------------------------------------------------------------------------------------------------------
13. Write a Python program to find the longest common prefix string amongst an array of strings. If
there is no common prefix, return an empty string.

In [34]:
def longest_common_prefix(strs):
    if not strs:
        return ""
    
    # Sort the array, so the smallest and largest strings are at the ends
    strs.sort()
    
    # Comparing characters of the first and last strings
    first = strs[0]
    last = strs[-1]
    i = 0
    
    # Find the common prefix between the first and last strings
    while i < len(first) and i < len(last) and first[i] == last[i]:
        i += 1
    
    # The common prefix will be the substring from the beginning to the matched length
    return first[:i]

# Having a Prefix.
strs = ["flower", "flow", "flight"]
result = longest_common_prefix(strs)
print("Longest common prefix:", result)

# Having no Prefix
strs_no_prefix = ["dog", "racecar", "car"]
result_no_prefix = longest_common_prefix(strs_no_prefix)
print("Longest common prefix:", result_no_prefix)


Longest common prefix: fl
Longest common prefix: 


---------------------------------------------------------------------------------------------------------------------------------------
14. Given a list of numbers, write a Python program to find the contiguous subarray which has the
largest sum and return its sum.

In [38]:
def max_subarray_sum(nums):
    # Initialize variables
    max_current = max_global = nums[0]
    
    # Iterate through the list starting from the second element
    for num in nums[1:]:
        # Update the maximum sum of the current subarray
        max_current = max(num, max_current + num)

        # Update the global maximum sum if the current subarray sum is greater
        if max_current > max_global:
            max_global = max_current
    
    return max_global

nums = [-2, 1, -3, 4, -1, 2, 1, -5, 4]
result = max_subarray_sum(nums)

print("The sum of the largest contiguous subarray is:", result)

The sum of the largest contiguous subarray is: 6


------------------------------------------------------------------------------------------------------------------------------------
15. Create a Python function that accepts a list of numbers and returns the list with each element
squared and filtered to only include results greater than 50.

In [40]:
def square_and_filter(nums):
    # Square each element and filter out those greater than 50
    return [num ** 2 for num in nums if num ** 2 > 50]

numbers = [2, 5, 7, 10, 3, 8]
result = square_and_filter(numbers)

print("Squared and filtered list:", result)

Squared and filtered list: [100, 64]


--------------------------------------------------------------------------------------------------------------------------------------
16. Write a Python program to merge two sorted lists into a new sorted list without using any built-in
sort functions.

In [42]:
def merge_sorted_lists(list1, list2):
    # Initialize pointers for list1 and list2
    i, j = 0, 0
    # Initialize the merged list
    merged_list = []
    
    # Traverse both lists and merge them in sorted order
    while i < len(list1) and j < len(list2):
        if list1[i] < list2[j]:
            merged_list.append(list1[i])
            i += 1
        else:
            merged_list.append(list2[j])
            j += 1
    
    # Append any remaining elements from list1
    while i < len(list1):
        merged_list.append(list1[i])
        i += 1
    
    # Append any remaining elements from list2
    while j < len(list2):
        merged_list.append(list2[j])
        j += 1
    
    return merged_list

list1 = [1, 3, 5, 7,9]
list2 = [2, 4, 6, 8]
result = merge_sorted_lists(list1, list2)

print("Merged sorted list:", result)

Merged sorted list: [1, 2, 3, 4, 5, 6, 7, 8, 9]


------------------------------------------------------------------------------------------------------------------------------------
17. Given a list of integers, write a Python program to find all unique triplets in the list which gives
the sum of zero.

In [43]:
def find_triplets(nums):
    nums.sort()  # Sorting the list.
    triplets = []
    n = len(nums)
    
    for i in range(n - 2):
        # Avoid duplicates for the first element of the triplet
        if i > 0 and nums[i] == nums[i - 1]:
            continue
        
        left, right = i + 1, n - 1
        while left < right:
            current_sum = nums[i] + nums[left] + nums[right]
            
            if current_sum == 0:
                triplets.append([nums[i], nums[left], nums[right]])
                
                # Avoid duplicates for the second and third elements of the triplet
                while left < right and nums[left] == nums[left + 1]:
                    left += 1
                
                while left < right and nums[right] == nums[right - 1]:
                    right -= 1
                
                left += 1
                right -= 1
            elif current_sum < 0:
                left += 1
            else:
                right -= 1
                
    return triplets

nums = [-1, 0, 1, 2, -1, -4]
result = find_triplets(nums)

print("Unique triplets that sum to zero:", result)

Unique triplets that sum to zero: [[-1, -1, 2], [-1, 0, 1]]


---------------------------------------------------------------------------------------------------------------------------------------
18. Write a Python program to generate a list of the first N Fibonacci numbers, where N is provided
by the user.

In [44]:
def generate_fibonacci(n):
    # Initializing the list with the first two Fibonacci numbers
    fibonacci_list = [0, 1]
    
    # Generate the next Fibonacci numbers until the list contains N elements
    while len(fibonacci_list) < n:
        next_fib = fibonacci_list[-1] + fibonacci_list[-2]
        fibonacci_list.append(next_fib)
    
    # If N is less than 2, adjust the list to contain exactly N elements
    return fibonacci_list[:n]

# Input from the user
n = int(input("Enter the number of Fibonacci numbers to generate: "))

# Generate the Fibonacci list
fibonacci_list = generate_fibonacci(n)

print(f"The first {n} Fibonacci numbers are: {fibonacci_list}")

Enter the number of Fibonacci numbers to generate:  17


The first 17 Fibonacci numbers are: [0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987]


-------------------------------------------------------------------------------------------------------------------------------------
19. Create a Python function that takes a string and returns True if it is an anagram of another string
provided as a second argument, otherwise returns False.

In [45]:
def are_anagrams(str1, str2):
    # Removing spaces and converting to lowercase.
    str1 = str1.replace(" ", "").lower()
    str2 = str2.replace(" ", "").lower()
    
    # Checks if both strings are equal
    return sorted(str1) == sorted(str2)

string1 = "listen"
string2 = "silent"
result = are_anagrams(string1, string2)
print(f"Are '{string1}' and '{string2}' anagrams? {result}")

string1 = "hello"
string2 = "world"
result = are_anagrams(string1, string2)
print(f"Are '{string1}' and '{string2}' anagrams? {result}")


Are 'listen' and 'silent' anagrams? True
Are 'hello' and 'world' anagrams? False


---------------------------------------------------------------------------------------------------------------------------------
20. Write a Python program to generate all permutations of a given string.

In [46]:
import itertools

def generate_permutations(s):
    # Generating all permutations of the string
    permutations = itertools.permutations(s)
    
    # Converting permutations to a list of strings
    permutation_list = [''.join(p) for p in permutations]
    
    return permutation_list

input_string = "abc"
result = generate_permutations(input_string)

print(f"All permutations of '{input_string}':")
for perm in result:
    print(perm)

All permutations of 'abc':
abc
acb
bac
bca
cab
cba


-------------------------------------------------------------------------------------------------------------------------------------
21. Given a matrix of size NxM, write a Python program to rotate the matrix 90 degrees clockwise.

In [51]:
N = 4

# Function to rotate the matrix 90 degree clockwise
def rotate90Clockwise(arr) :
	global N
	
	for j in range(N) :
		for i in range(N - 1, -1, -1) :
			print(arr[i][j], end = " ")
		print()
			 
arr = [ [ 1, 2, 3, 4 ],
		[ 5, 6, 7, 8 ],
		[ 9, 10, 11, 12 ],
		[ 13, 14, 15, 16 ] ]
rotate90Clockwise(arr);

13 9 5 1 
14 10 6 2 
15 11 7 3 
16 12 8 4 


-----------------------------------------------------------------------------------------------------------------------------------
22. Create a Python function that checks if a given number is a palindrome without converting it to a
string.

In [52]:
def is_palindrome_number(num):
    # Negative numbers are not palindromes
    if num < 0:
        return False

    original_num = num
    reversed_num = 0
    
    # Reversing the number
    while num > 0:
        remainder = num % 10
        reversed_num = reversed_num * 10 + remainder
        num //= 10
    
    # Checking if the original number is equal to the reversed number
    return original_num == reversed_num

number = 12321
result = is_palindrome_number(number)
print(f"Is {number} a palindrome? {result}")

number = 12345
result = is_palindrome_number(number)
print(f"Is {number} a palindrome? {result}")


Is 12321 a palindrome? True
Is 12345 a palindrome? False


--------------------------------------------------------------------------------------------------------------------------------------
23. Write a Python program to find the first non-repeating character in a string and return its index. If
it doesn't exist, return -1.

In [53]:
def first_non_repeating_character(s):
    # A dictionary to store the frequency of each character
    char_count = {}
    
    # Counting the frequency of each character
    for char in s:
        if char in char_count:
            char_count[char] += 1
        else:
            char_count[char] = 1
    
    # Finding the index of the first non-repeating character
    for index, char in enumerate(s):
        if char_count[char] == 1:
            return index
    
    # Return -1 if no non-repeating character is found
    return -1

input_string = "swiss"
result = first_non_repeating_character(input_string)
print(f"The index of the first non-repeating character is: {result}")

input_string = "aabbcc"
result = first_non_repeating_character(input_string)
print(f"The index of the first non-repeating character is: {result}")


The index of the first non-repeating character is: 1
The index of the first non-repeating character is: -1


------------------------------------------------------------------------------------------------------------------------------------
24. Given two strings, write a Python program to find the minimum window in the first string which
will contain all the characters in the second string.

In [54]:
from collections import Counter, defaultdict

def min_window(s1, s2):
    if not s1 or not s2:
        return ""
    
    # A dictionary to count the characters in s2
    char_count_s2 = Counter(s2)
    required = len(char_count_s2)
    
    # Initializing pointers and variables
    left, right = 0, 0
    formed = 0
    window_counts = defaultdict(int)
    min_len = float('inf')
    min_window = ""
    
    # Start sliding the window
    while right < len(s1):
        # Add the character from the right pointer to the window
        char = s1[right]
        window_counts[char] += 1
        
        # Check if the current character helps in forming the required substring
        if char in char_count_s2 and window_counts[char] == char_count_s2[char]:
            formed += 1
        
        while left <= right and formed == required:
            char = s1[left]
            
            # Update the minimum window
            if right - left + 1 < min_len:
                min_len = right - left + 1
                min_window = s1[left:right + 1]
            
            # Remove the character at the left pointer from the window
            window_counts[char] -= 1
            if char in char_count_s2 and window_counts[char] < char_count_s2[char]:
                formed -= 1
            
            left += 1
        
        # Move the right pointer to expand the window
        right += 1
    
    return min_window

s1 = "ADOBECODEBANC"
s2 = "ABC"
result = min_window(s1, s2)
print(f"The minimum window in '{s1}' which contains all characters of '{s2}' is: '{result}'")

s1 = "AABBC"
s2 = "ABC"
result = min_window(s1, s2)
print(f"The minimum window in '{s1}' which contains all characters of '{s2}' is: '{result}'")


The minimum window in 'ADOBECODEBANC' which contains all characters of 'ABC' is: 'BANC'
The minimum window in 'AABBC' which contains all characters of 'ABC' is: 'ABBC'


-------------------------------------------------------------------------------------------------------------------------------
25. Write a Python program to solve the Tower of Hanoi problem using recursion.

In [57]:
def tower_of_hanoi(n, source, auxiliary, target):
    if n == 1:
        print(f"Move disk 1 from {source} to {target}")
        return
    
    # Move n-1 disks from source to auxiliary, so they are out of the way
    tower_of_hanoi(n - 1, source, target, auxiliary)
    
    # Move the nth disk from source to target
    print(f"Move disk {n} from {source} to {target}")
    
    # Move the n-1 disks from auxiliary to target
    tower_of_hanoi(n - 1, auxiliary, source, target)

n = 4  # Number of disks
tower_of_hanoi(n, 'A', 'B', 'C')


Move disk 1 from A to B
Move disk 2 from A to C
Move disk 1 from B to C
Move disk 3 from A to B
Move disk 1 from C to A
Move disk 2 from C to B
Move disk 1 from A to B
Move disk 4 from A to C
Move disk 1 from B to C
Move disk 2 from B to A
Move disk 1 from C to A
Move disk 3 from B to C
Move disk 1 from A to B
Move disk 2 from A to C
Move disk 1 from B to C


-------------------------------------------------------------------------------------------------------------------------------------
26. Create a Python function to convert a given Roman numeral to an integer.

In [58]:
def roman_to_integer(roman):
    # Define a dictionary to map Roman numerals to their integer values
    roman_values = {
        'I': 1,
        'V': 5,
        'X': 10,
        'L': 50,
        'C': 100,
        'D': 500,
        'M': 1000
    }
    
    # Initializing the total integer value
    total = 0
    prev_value = 0
    
    # Iterate through the Roman numeral from left to right
    for char in roman:
        value = roman_values[char]
        
        if prev_value < value:
            total += value - 2 * prev_value
        else:
            total += value
        
        prev_value = value
    
    return total

roman_numeral = "MCMXCIV"  # 1994
result = roman_to_integer(roman_numeral)
print(f"The integer value of Roman numeral '{roman_numeral}' is: {result}")

roman_numeral = "LVIII"  # 58
result = roman_to_integer(roman_numeral)
print(f"The integer value of Roman numeral '{roman_numeral}' is: {result}")


The integer value of Roman numeral 'MCMXCIV' is: 1994
The integer value of Roman numeral 'LVIII' is: 58


---------------------------------------------------------------------------------------------------------------------------------
27. Write a Python program to implement a simple calculator that can perform basic arithmetic
operations (+, -, *, /) on two numbers provided by the user.

In [60]:
def simple_calculator():
    # Get user input for the two numbers and the operation
    try:
        num1 = float(input("Enter the first number: "))
        num2 = float(input("Enter the second number: "))
        
        print("Select operation:")
        print("1. Addition (+)")
        print("2. Subtraction (-)")
        print("3. Multiplication (*)")
        print("4. Division (/)")

        operation = input("Enter the operation (+, -, *, /): ")

        # Perform the chosen operation
        if operation == '+':
            result = num1 + num2
            print(f"The result of {num1} + {num2} is: {result}")
        elif operation == '-':
            result = num1 - num2
            print(f"The result of {num1} - {num2} is: {result}")
        elif operation == '*':
            result = num1 * num2
            print(f"The result of {num1} * {num2} is: {result}")
        elif operation == '/':
            # Handle division by zero
            if num2 == 0:
                print("Error: Division by zero is not allowed.")
            else:
                result = num1 / num2
                print(f"The result of {num1} / {num2} is {result}")
        else:
            print("Invalid operation. Please enter one of the following: +, -, *, /")
    
    except ValueError:
        print("Invalid input. Please enter numeric values for the numbers.")

simple_calculator()

Enter the first number:  4
Enter the second number:  5


Select operation:
1. Addition (+)
2. Subtraction (-)
3. Multiplication (*)
4. Division (/)


Enter the operation (+, -, *, /):  +


The result of 4.0 + 5.0 is: 9.0


--------------------------------------------------------------------------------------------------------------------------------------
28. Given a binary tree, write a Python program to perform in-order, pre-order, and post-order traversals.

In [62]:
class TreeNode:
    def __init__(self, value=0, left=None, right=None):
        self.value = value
        self.left = left
        self.right = right

def in_order_traversal(root):
    if root:
        in_order_traversal(root.left)  # Visit left subtree
        print(root.value, end=' ')    # Visit node
        in_order_traversal(root.right) # Visit right subtree

def pre_order_traversal(root):
    if root:
        print(root.value, end=' ')    # Visit node
        pre_order_traversal(root.left)  # Visit left subtree
        pre_order_traversal(root.right) # Visit right subtree

def post_order_traversal(root):
    if root:
        post_order_traversal(root.left)  # Visit left subtree
        post_order_traversal(root.right) # Visit right subtree
        print(root.value, end=' ')    # Visit node

if __name__ == "__main__":
    # Create a binary tree
    #       1
    #      / \
    #     2   3
    #    / \
    #   4   5
    root = TreeNode(1)
    root.left = TreeNode(2)
    root.right = TreeNode(3)
    root.left.left = TreeNode(4)
    root.left.right = TreeNode(5)

    print("In-order traversal:")
    in_order_traversal(root)  # Output: 4 2 5 1 3
    print("\nPre-order traversal:")
    pre_order_traversal(root)  # Output: 1 2 4 5 3
    print("\nPost-order traversal:")
    post_order_traversal(root)  # Output: 4 5 2 3 1


In-order traversal:
4 2 5 1 3 
Pre-order traversal:
1 2 4 5 3 
Post-order traversal:
4 5 2 3 1 

--------------------------------------------------------------------------------------------------------------------------------------
29. Write a Python program to find the maximum depth of a binary tree.

In [63]:
class TreeNode:
    def __init__(self, value=0, left=None, right=None):
        self.value = value
        self.left = left
        self.right = right

def max_depth(root):
    # If the tree is empty, return depth of 0
    if root is None:
        return 0
    
    # Recursively find the depth of the left and right subtrees
    left_depth = max_depth(root.left)
    right_depth = max_depth(root.right)

    return max(left_depth, right_depth) + 1

if __name__ == "__main__":
    # Create a binary tree
    #       1
    #      / \
    #     2   3
    #    / \
    #   4   5
    root = TreeNode(1)
    root.left = TreeNode(2)
    root.right = TreeNode(3)
    root.left.left = TreeNode(4)
    root.left.right = TreeNode(5)

    depth = max_depth(root)
    print(f"The maximum depth of the binary tree is: {depth}")

The maximum depth of the binary tree is: 3


-------------------------------------------------------------------------------------------------------------------------------------
30. Create a Python function that takes a list of integers and a target number and returns the indices
of the two numbers that add up to the target.

In [64]:
def two_sum(nums, target):
    # A Dictionary to store the indices of numbers we've seen
    index_map = {}

    for index, num in enumerate(nums):
        complement = target - num
        
        # Check if the complement number exists in the dictionary
        if complement in index_map:
            return [index_map[complement], index]
        
        index_map[num] = index

    return []

nums = [2, 7, 11, 15]
target = 9
result = two_sum(nums, target)
print(f"The indices of the two numbers that add up to {target} are: {result}")

nums = [3, 2, 4]
target = 6
result = two_sum(nums, target)
print(f"The indices of the two numbers that add up to {target} are: {result}")

nums = [1, 2, 3, 4]
target = 10
result = two_sum(nums, target)
print(f"The indices of the two numbers that add up to {target} are: {result}")


The indices of the two numbers that add up to 9 are: [0, 1]
The indices of the two numbers that add up to 6 are: [1, 2]
The indices of the two numbers that add up to 10 are: []


-----------------------------------------------------------------------------------------------------------------------------------
31. Write a Python program to implement a stack with push, pop, and min functions, where the min
function returns the minimum element in the stack in O(1) time.

In [65]:
class MinStack:
    def __init__(self):
        self.stack = []        # Main stack to store the elements
        self.min_stack = []    # Auxiliary stack to store the minimum elements

    def push(self, x):
        self.stack.append(x)
        # Push the element onto the min stack if it's smaller than or equal to the current minimum
        if not self.min_stack or x <= self.min_stack[-1]:
            self.min_stack.append(x)

    def pop(self):
        if not self.stack:
            return None
        # Pop the element from the main stack
        top = self.stack.pop()
        # Pop the element from the min stack if it's the same as the top of the main stack
        if top == self.min_stack[-1]:
            self.min_stack.pop()
        return top

    def top(self):
        if not self.stack:
            return None
        return self.stack[-1]

    def get_min(self):
        if not self.min_stack:
            return None
        return self.min_stack[-1]

min_stack = MinStack()
min_stack.push(3)
min_stack.push(5)
print(f"Current minimum: {min_stack.get_min()}")  # Output: 3

min_stack.push(2)
min_stack.push(1)
print(f"Current minimum: {min_stack.get_min()}")  # Output: 1

min_stack.pop()
print(f"Current minimum: {min_stack.get_min()}")  # Output: 2

min_stack.pop()
print(f"Current minimum: {min_stack.get_min()}")  # Output: 3

min_stack.push(0)
print(f"Current minimum: {min_stack.get_min()}")  # Output: 0


Current minimum: 3
Current minimum: 1
Current minimum: 2
Current minimum: 3
Current minimum: 0


-------------------------------------------------------------------------------------------------------------------------------------
32. Given a string containing just the characters '(', ')', '{', '}', '[' and ']', write a Python program to
check if the input string is valid.

In [1]:
def is_valid(s: str) -> bool:
    bracket_map = {')': '(', '}': '{', ']': '['}
    
    stack = []

    for char in s:
        if char in bracket_map:
            top_element = stack.pop() if stack else '#'
            
            if bracket_map[char] != top_element:
                return False
        else:
            stack.append(char)

    return not stack

input_string = "{[()]}"
print(is_valid(input_string))  # True

input_string = "{[(])}"
print(is_valid(input_string))  # False


True
False


------------------------------------------------------------------------------------------------------------------------------------------
33. Write a Python program to generate a random password with a given length. The password
should contain a mix of uppercase and lowercase letters, numbers, and special characters.

In [3]:
import random
import string

def generate_password(length: int) -> str:
    all_characters = string.ascii_letters + string.digits + string.punctuation

    password = [
        random.choice(string.ascii_lowercase),
        random.choice(string.ascii_uppercase),
        random.choice(string.digits),
        random.choice(string.punctuation)
    ]
    
    if length > 4:
        password += random.choices(all_characters, k=length-4)
    
    random.shuffle(password)

    return ''.join(password)

password_length = 10
password = generate_password(password_length)
print(f"Generated password: {password}")


Generated password: R\k|BK#4=Y


----------------------------------------------------------------------------------------------------------------------------------------
34. Create a Python function that simulates the roll of a six-sided die N times and returns the
frequency of each outcome.

In [4]:
import random
from collections import defaultdict

def roll_die_n_times(n: int) -> dict:
    frequency = defaultdict(int)

    for _ in range(n):
        outcome = random.randint(1, 6)
        frequency[outcome] += 1

    return dict(frequency)

n = 1000
frequencies = roll_die_n_times(n)
print(f"Frequencies of each outcome after rolling the die {n} times:")
for outcome, freq in frequencies.items():
    print(f"{outcome}: {freq}")


Frequencies of each outcome after rolling the die 1000 times:
3: 181
4: 163
5: 158
6: 164
2: 176
1: 158


---------------------------------------------------------------------------------------------------------------------------------------
35. Write a Python program to implement a queue using two stacks.

In [5]:
class QueueUsingStacks:
    def __init__(self):
        self.stack1 = []
        self.stack2 = []

    def enqueue(self, item):
        self.stack1.append(item)

    def dequeue(self):
        if not self.stack2:
            while self.stack1:
                self.stack2.append(self.stack1.pop())
       
        if not self.stack2:
            raise IndexError("Dequeue from an empty queue")
        return self.stack2.pop()

queue = QueueUsingStacks()
queue.enqueue(1)
queue.enqueue(2)
queue.enqueue(3)
print(queue.dequeue())  # 1
print(queue.dequeue())  # 2
queue.enqueue(4)
print(queue.dequeue())  # 3
print(queue.dequeue())  # 4


1
2
3
4


---------------------------------------------------------------------------------------------------------------------------------------
36. Create a Python function to check if a given string is a valid IP address.

In [6]:
def is_valid_ip(ip: str) -> bool:
    parts = ip.split('.')
    
    if len(parts) != 4:
        return False
    
    for part in parts:
        if not part.isdigit():
            return False

        num = int(part)

        if num < 0 or num > 255:
            return False

        if part != str(num):
            return False
    
    return True

ip_addresses = ["192.168.1.1", "255.255.255.255", "192.168.1.256", "123.045.067.089"]
for ip in ip_addresses:
    print(f"{ip} is valid: {is_valid_ip(ip)}")


192.168.1.1 is valid: True
255.255.255.255 is valid: True
192.168.1.256 is valid: False
123.045.067.089 is valid: False


------------------------------------------------------------------------------------------------------------------------------------
37. Write a Python program to find the length of the longest substring without repeating characters.

In [7]:
def length_of_longest_substring(s: str) -> int:
    char_index_map = {}
    left = 0
    max_length = 0

    for right, char in enumerate(s):
        if char in char_index_map and char_index_map[char] >= left:
            left = char_index_map[char] + 1
        char_index_map[char] = right
        max_length = max(max_length, right - left + 1)

    return max_length

input_string = "abcabcbb"
print(f"Length of the longest substring without repeating characters: {length_of_longest_substring(input_string)}")

input_string = "bbbbb"
print(f"Length of the longest substring without repeating characters: {length_of_longest_substring(input_string)}")

input_string = "pwwkew"
print(f"Length of the longest substring without repeating characters: {length_of_longest_substring(input_string)}")


Length of the longest substring without repeating characters: 3
Length of the longest substring without repeating characters: 1
Length of the longest substring without repeating characters: 3


--------------------------------------------------------------------------------------------------------------------------------------
38. Given a string, write a Python program to check if it can be rearranged to form a palindrome.

In [8]:
from collections import Counter

def can_form_palindrome(s: str) -> bool:
    char_count = Counter(s)

    odd_count = sum(1 for count in char_count.values() if count % 2 != 0)

    return odd_count <= 1

input_string = "civic"
print(f"Can '{input_string}' be rearranged to form a palindrome? {can_form_palindrome(input_string)}")

input_string = "ivicc"
print(f"Can '{input_string}' be rearranged to form a palindrome? {can_form_palindrome(input_string)}")

input_string = "hello"
print(f"Can '{input_string}' be rearranged to form a palindrome? {can_form_palindrome(input_string)}")

input_string = "aabbccdde"
print(f"Can '{input_string}' be rearranged to form a palindrome? {can_form_palindrome(input_string)}")


Can 'civic' be rearranged to form a palindrome? True
Can 'ivicc' be rearranged to form a palindrome? True
Can 'hello' be rearranged to form a palindrome? False
Can 'aabbccdde' be rearranged to form a palindrome? True


-------------------------------------------------------------------------------------------------------------------------------------
39. Create a Python function that generates all possible combinations of a given list of numbers.

In [10]:
import itertools

def generate_combinations(numbers):
    all_combinations = []
    for r in range(1, len(numbers) + 1):
        combinations_r = itertools.combinations(numbers, r)
        all_combinations.extend(combinations_r)
    return all_combinations

numbers = [1, 2, 3, 4]
combinations = generate_combinations(numbers)
print("All possible combinations of the list:")
for combo in combinations:
    print(combo)


All possible combinations of the list:
(1,)
(2,)
(3,)
(4,)
(1, 2)
(1, 3)
(1, 4)
(2, 3)
(2, 4)
(3, 4)
(1, 2, 3)
(1, 2, 4)
(1, 3, 4)
(2, 3, 4)
(1, 2, 3, 4)


--------------------------------------------------------------------------------------------------------------------------------------
40. Write a Python program to implement the Sieve of Eratosthenes algorithm to find all prime
numbers less than a given number.

In [11]:
def sieve_of_eratosthenes(n):
    primes = [True] * n
    primes[0] = primes[1] = False  # 0 and 1 are not prime numbers

    for i in range(2, int(n**0.5) + 1):
        if primes[i]:
            for j in range(i*i, n, i):
                primes[j] = False

    prime_numbers = [i for i, is_prime in enumerate(primes) if is_prime]
    return prime_numbers

n = 50
prime_numbers = sieve_of_eratosthenes(n)
print(f"Prime numbers less than {n}: {prime_numbers}")


Prime numbers less than 50: [2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47]


-------------------------------------------------------------------------------------------------------------------------------------
41. Create a Python function that takes a list of words and returns the list sorted by the length of the
words in ascending order.

In [12]:
def sort_by_length(words):
    return sorted(words, key=len)

words = ["apple", "banana", "cherry", "date", "elderberry", "fig", "grape"]
sorted_words = sort_by_length(words)
print("Words sorted by length:", sorted_words)


Words sorted by length: ['fig', 'date', 'apple', 'grape', 'banana', 'cherry', 'elderberry']


-------------------------------------------------------------------------------------------------------------------------------------
42. Write a Python program to perform matrix multiplication for two given matrices.

In [13]:
def matrix_multiply(A, B):
    rows_A = len(A)
    cols_A = len(A[0])
    rows_B = len(B)
    cols_B = len(B[0])

    if cols_A != rows_B:
        raise ValueError("Number of columns in A must be equal to the number of rows in B")

    result = [[0] * cols_B for _ in range(rows_A)]
    
    for i in range(rows_A):
        for j in range(cols_B):
            result[i][j] = sum(A[i][k] * B[k][j] for k in range(cols_A))
    
    return result

A = [
    [1, 2, 3],
    [4, 5, 6]
]

B = [
    [7, 8],
    [9, 10],
    [11, 12]
]

result = matrix_multiply(A, B)
print("Result of matrix multiplication:")
for row in result:
    print(row)


Result of matrix multiplication:
[58, 64]
[139, 154]


---------------------------------------------------------------------------------------------------------------------------------------
43. Create a Python function that finds the smallest missing positive integer in an unsorted list.

In [21]:
def first_missing_positive(nums):
    n = len(nums)

    for i in range(n):
        if nums[i] <= 0 or nums[i] > n:
            nums[i] = n + 1

    for i in range(n):
        num = abs(nums[i])
        if num <= n:
            nums[num - 1] = -abs(nums[num - 1])
    
    for i in range(n):
        if nums[i] > 0:
            return i + 1
    
    return n + 1

nums = [3, 4, -1, 1]
missing_positive = first_missing_positive(nums)
print(f"The smallest missing positive integer in the list {nums} is: {missing_positive}")

The smallest missing positive integer in the list [-3, 4, -5, -1] is: 2


----------------------------------------------------------------------------------------------------------------------------------------
44. Write a Python program to implement the binary search algorithm on a sorted list of numbers.

In [22]:
def binary_search(sorted_list, target):
    left, right = 0, len(sorted_list) - 1
    
    while left <= right:
        mid = (left + right) // 2
        mid_value = sorted_list[mid]
        
        if mid_value == target:
            return mid  
        elif mid_value < target:
            left = mid + 1 
        else:
            right = mid - 1  
    
    return -1  

sorted_list = [1, 3, 5, 7, 9, 11, 13, 15, 17, 19]
target = 7
index = binary_search(sorted_list, target)
print(f"Index of {target} in the sorted list: {index}")

target = 4
index = binary_search(sorted_list, target)
print(f"Index of {target} in the sorted list: {index}")


Index of 7 in the sorted list: 3
Index of 4 in the sorted list: -1


------------------------------------------------------------------------------------------------------------------------------------
45. Given a list of numbers, write a Python program to find the second largest number in the list.

In [23]:
def find_second_largest(numbers):
    if len(numbers) < 2:
        raise ValueError("List must contain at least two numbers")

    largest = second_largest = float('-inf')
    
    for num in numbers:
        if num > largest:
            second_largest = largest
            largest = num
        elif num > second_largest and num < largest:
            second_largest = num
    
    if second_largest == float('-inf'):
        raise ValueError("There is no second largest number in the list")
    
    return second_largest

numbers = [10, 5, 20, 20, 30]
print(f"The second largest number in the list is: {find_second_largest(numbers)}")

numbers = [15]
try:
    print(f"The second largest number in the list is: {find_second_largest(numbers)}")
except ValueError as e:
    print(e)


The second largest number in the list is: 20
List must contain at least two numbers


--------------------------------------------------------------------------------------------------------------------------------------
46. Create a Python function that takes a string and returns the number of vowels and consonants in
it.

In [24]:
def count_vowels_and_consonants(s):
    vowels = "aeiouAEIOU"
    vowel_count = 0
    consonant_count = 0

    for char in s:
        if char.isalpha():  
            if char in vowels:
                vowel_count += 1
            else:
                consonant_count += 1

    return vowel_count, consonant_count

input_string = "Hello, World!"
vowels, consonants = count_vowels_and_consonants(input_string)
print(f"Number of vowels: {vowels}")
print(f"Number of consonants: {consonants}")


Number of vowels: 3
Number of consonants: 7


-----------------------------------------------------------------------------------------------------------------------------------------
47. Write a Python program to check if a given number is a power of two.

In [25]:
def is_power_of_two(n):
    return n > 0 and (n & (n - 1)) == 0

numbers = [1, 2, 3, 4, 5, 8, 12, 16]
results = {num: is_power_of_two(num) for num in numbers}

for num, result in results.items():
    print(f"{num} is a power of two: {result}")


1 is a power of two: True
2 is a power of two: True
3 is a power of two: False
4 is a power of two: True
5 is a power of two: False
8 is a power of two: True
12 is a power of two: False
16 is a power of two: True


---------------------------------------------------------------------------------------------------------------------------------------
48. Create a Python function to reverse the words in a given sentence.

In [26]:
def reverse_words(sentence):
    words = sentence.split()

    reversed_words = words[::-1]

    reversed_sentence = ' '.join(reversed_words)
    
    return reversed_sentence

sentence = "Hello world this is a test"
reversed_sentence = reverse_words(sentence)
print(f"Original sentence: '{sentence}'")
print(f"Reversed sentence: '{reversed_sentence}'")


Original sentence: 'Hello world this is a test'
Reversed sentence: 'test a is this world Hello'


----------------------------------------------------------------------------------------------------------------------------------------
49. Write a Python program to calculate the factorial of a number using both iterative and recursive
methods.

In [27]:
# Iterative Method
def factorial_iterative(n):
    if n < 0:
        raise ValueError("Factorial is not defined for negative numbers")
    
    result = 1
    for i in range(1, n + 1):
        result *= i
    return result

# Recursive Method
def factorial_recursive(n):
    if n < 0:
        raise ValueError("Factorial is not defined for negative numbers")
    if n == 0 or n == 1:
        return 1
    return n * factorial_recursive(n - 1)

number = 5

print(f"Factorial of {number} using iterative method: {factorial_iterative(number)}")
print(f"Factorial of {number} using recursive method: {factorial_recursive(number)}")

print(f"\nFactorial of {number} using iterative method: {factorial_iterative(number)}")
print(f"Factorial of {number} using recursive method: {factorial_recursive(number)}")

Factorial of 5 using iterative method: 120
Factorial of 5 using recursive method: 120

Factorial of 5 using iterative method: 120
Factorial of 5 using recursive method: 120


---------------------------------------------------------------------------------------------------------------------------------------
50. Given a list of integers, write a Python program to find the maximum product of two integers inthe list.

In [28]:
def max_product_of_two(numbers):
    if len(numbers) < 2:
        raise ValueError("The list must contain at least two numbers")

    numbers.sort()

    max_product = max(numbers[0] * numbers[1], numbers[-1] * numbers[-2])
    
    return max_product

numbers = [1, 10, -5, -10, 0, 2]
print(f"The maximum product of two integers in the list is: {max_product_of_two(numbers)}")

numbers = [3, 5, 1, 2, 4]
print(f"The maximum product of two integers in the list is: {max_product_of_two(numbers)}")

numbers = [-1, -2, -3, -4]
print(f"The maximum product of two integers in the list is: {max_product_of_two(numbers)}")


The maximum product of two integers in the list is: 50
The maximum product of two integers in the list is: 20
The maximum product of two integers in the list is: 12


--------------------------------------------------------------------------------------------------------------------------------------------

--------------------------------------------------------------------------------------------------------------------------------------------

--------------------------------------------------------------------------------------------------------------------------------------------